# Generated by Django 4.1.4 on 2023-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('img_path', models.CharField(max_length=64)),
                ('in_stock_flag', models.BooleanField()),
                ('url_path', models.CharField(max_length=64)),
            ],
        ),
    ]
